# Generated by Django 3.2.6 on 2021-08-29 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchatmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatechatroom',
            name='user1',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_admin': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatechatroom',
            name='user2',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_admin': True}, null=True, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
