# Generated by Django 3.2.5 on 2021-08-21 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechatroom',
            name='session_ID',
            field=models.CharField(default=django.utils.timezone.now, max_length=215),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privatechatroom',
            name='user1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatechatroom',
            name='user2',
            field=models.ForeignKey(limit_choices_to={'is_admin': True}, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
