# Generated by Django 3.2.5 on 2021-08-21 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat', '0003_auto_20210821_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatroom',
            name='user1',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_admin': False}, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
    ]
