# Generated by Django 3.2.5 on 2021-08-21 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat', '0005_auto_20210821_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechatroom',
            name='user2',
        ),
        migrations.AddField(
            model_name='privatechatroom',
            name='user2',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
