# Generated by Django 3.2.5 on 2021-08-21 23:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat', '0006_auto_20210821_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechatroom',
            name='user2',
        ),
        migrations.AddField(
            model_name='privatechatroom',
            name='user2',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_admin': True}, null=True, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
