# Generated by Django 3.2.6 on 2021-08-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now=True, verbose_name='last modified')),
                ('date_published', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('CNT_CHILDREN', models.IntegerField()),
                ('AMT_INCOME_TOTAL', models.IntegerField()),
                ('DAYS_BIRTH', models.DateField()),
                ('DAYS_EMPLOYED', models.DateField()),
                ('FLAG_MOBIL', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=115)),
                ('FLAG_WORK_PHONE', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=115)),
                ('FLAG_PHONE', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=115)),
                ('FLAG_EMAIL', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=115)),
                ('CNT_FAM_MEMBERS', models.IntegerField()),
                ('CODE_GENDER', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=115)),
                ('FLAG_OWN_CAR', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=115)),
                ('FLAG_OWN_REALTY', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=115)),
                ('NAME_INCOME_TYPE', models.CharField(choices=[('Commercial associate', 'Commercial associate'), ('Pensioner', 'Pensioner'), ('State servant', 'State servant'), ('Student', 'Student'), ('Working', 'Working')], max_length=115)),
                ('NAME_EDUCATION_TYPE', models.CharField(choices=[('Academic degree', 'Academic degree'), ('Higher education', 'Higher education'), ('Incomplete higher', 'Incomplete higher'), ('Lower secondary', 'Lower secondary'), ('Secondary / secondary special', 'Secondary / secondary special')], max_length=115)),
                ('NAME_FAMILY_STATUS', models.CharField(choices=[('Civil marriage', 'Civil marriage'), ('Married', 'Married'), ('Separated', 'Separated'), ('Single / not married', 'Single / not married'), ('Widow', 'Widow')], max_length=115)),
                ('NAME_HOUSING_TYPE', models.CharField(choices=[('Co-op apartment', 'Co-op apartment'), ('House / apartment', 'House / apartment'), ('Municipal apartment', 'Municipal apartment'), ('Office apartment', 'Office apartment'), ('Rented apartment', 'Rented apartment'), ('With parents', 'With parents')], max_length=115)),
                ('OCCUPATION_TYPE', models.CharField(choices=[('Accountants', 'Accountants'), ('Cleaning staff', 'Cleaning staff'), ('Cooking staff ', 'Cooking staff '), ('Core staff', 'Core staff'), ('Drivers', 'Drivers'), ('HR staff', 'HR staff'), ('High skill tech staff', 'High skill tech staff'), ('IT staff', 'IT staff'), ('Laborers', 'Laborers'), ('Low-skill Laborers', 'Low-skill Laborers'), ('Managers', 'Managers'), ('Medicine staff', 'Medicine staff'), ('Private service staff', 'Private service staff'), ('Realty agents', 'Realty agents'), ('Sales staff', 'Sales staff'), ('Secretaries', 'Secretaries'), ('Security staff', 'Security staff'), ('Waiters/barmen staff', 'Waiters/barmen staff'), ('Unknown', 'Unknown')], max_length=115)),
                ('Result', models.CharField(choices=[('0', 'Approved'), ('1', 'Rejected')], max_length=115)),
                ('Feedback', models.CharField(blank=True, choices=[('0', 'Approved'), ('1', 'Rejected')], max_length=115)),
            ],
        ),
    ]
