# Generated by Django 3.2.5 on 2021-08-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20210816_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvals',
            name='FLAG_EMAIL',
            field=models.CharField(choices=[(1, 'Yes'), (0, 'No')], max_length=115),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='FLAG_MOBIL',
            field=models.CharField(choices=[(1, 'Yes'), (0, 'No')], max_length=115),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='FLAG_OWN_CAR',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=115),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='FLAG_PHONE',
            field=models.CharField(choices=[(1, 'Yes'), (0, 'No')], max_length=115),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='FLAG_WORK_PHONE',
            field=models.CharField(choices=[(1, 'Yes'), (0, 'No')], max_length=115),
        ),
    ]
