# Generated by Django 3.2.5 on 2021-08-17 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_auto_20210816_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='approvals',
            name='date_published',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
